/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.95
 * Generated at: 2025-12-09 09:43:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.math.BigInteger;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("java.math.BigInteger");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"vi\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Hệ thống Chữ ký số ElGamal</title>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        function readFile(input, targetId) {\r\n");
      out.write("            let file = input.files[0];\r\n");
      out.write("            if (!file) return;\r\n");
      out.write("            let reader = new FileReader();\r\n");
      out.write("            reader.onload = function() {\r\n");
      out.write("                document.getElementById(targetId).value = reader.result;\r\n");
      out.write("            };\r\n");
      out.write("            reader.readAsText(file);\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <h1>Chữ Ký Số ElGamal</h1>\r\n");
      out.write("    <p class=\"subtitle\">Thực hiện theo thứ tự từ Bước 1 → Bước 2 → Bước 3</p>\r\n");
      out.write("\r\n");
      out.write("    ");
 if(request.getAttribute("error") != null) { 
      out.write("\r\n");
      out.write("        <div class=\"alert alert-danger\">");
      out.print( request.getAttribute("error") );
      out.write("</div>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");

        String signR = (String) request.getAttribute("sign_r");
        String signS = (String) request.getAttribute("sign_s");
        String lastSignedDoc = (String) request.getAttribute("last_signed_doc");

        if (signR == null) signR = (String) session.getAttribute("sign_r_session");
        if (signS == null) signS = (String) session.getAttribute("sign_s_session");
        if (lastSignedDoc == null) lastSignedDoc = (String) session.getAttribute("last_signed_doc_session");

        String docContentValue = (String) request.getParameter("docContent");
        if (docContentValue == null) docContentValue = (lastSignedDoc != null ? lastSignedDoc : "");
    
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"grid-container\">\r\n");
      out.write("\r\n");
      out.write("        <!-- BƯỚC 1 -->\r\n");
      out.write("        <div class=\"card\">\r\n");
      out.write("            <div class=\"card-header\">BƯỚC 1: TẠO KHÓA</div>\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("                <form action=\"process\" method=\"post\">\r\n");
      out.write("                    <input type=\"hidden\" name=\"action\" value=\"generateKeys\">\r\n");
      out.write("\r\n");
      out.write("                    <label>p (số nguyên tố)</label>\r\n");
      out.write("                    <input type=\"text\" name=\"p\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.key_p != null ? sessionScope.key_p : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("                    <label>alpha (căn nguyên)</label>\r\n");
      out.write("                    <input type=\"text\" name=\"alpha\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.key_alpha != null ? sessionScope.key_alpha : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("                    <label>Khóa bí mật x</label>\r\n");
      out.write("                    <input type=\"text\" name=\"x\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.key_x != null ? sessionScope.key_x : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"single-button-row\">\r\n");
      out.write("                        <button type=\"submit\" name=\"genMode\" value=\"input\" class=\"btn btn-primary\">Tạo khóa từ đầu vào</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"divider-text\">hoặc</div>\r\n");
      out.write("\r\n");
      out.write("                    <button type=\"submit\" name=\"genMode\" value=\"random\" class=\"btn btn-success\">Tạo khóa ngẫu nhiên</button>\r\n");
      out.write("                </form>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"result-box\">\r\n");
      out.write("                    <strong>Khóa Đã Sinh:</strong>\r\n");
      out.write("                    ");
 if(session.getAttribute("key_p") != null) { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        <!-- ĐÃ XÓA p và alpha theo yêu cầu -->\r\n");
      out.write("                        <div class=\"key-row\">\r\n");
      out.write("                            <span class=\"key-label\">x (khóa bí mật):</span>\r\n");
      out.write("                            <span class=\"key-value\">");
      out.print( session.getAttribute("key_x") );
      out.write("</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"key-row\">\r\n");
      out.write("                            <span class=\"key-label\">y (khóa công khai):</span>\r\n");
      out.write("                            <span class=\"key-value\">");
      out.print( session.getAttribute("key_y") );
      out.write("</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    ");
 } else { 
      out.write("\r\n");
      out.write("                        <div class=\"placeholder\">Chưa có khóa. Hãy tạo khóa.</div>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- BƯỚC 2 -->\r\n");
      out.write("        <div class=\"card\">\r\n");
      out.write("            <div class=\"card-header\">BƯỚC 2: KÝ TÀI LIỆU</div>\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("                <form action=\"process\" method=\"post\">\r\n");
      out.write("                    <input type=\"hidden\" name=\"action\" value=\"sign\">\r\n");
      out.write("\r\n");
      out.write("                    <label>Văn bản cần ký</label>\r\n");
      out.write("                    <textarea name=\"docContent\" id=\"docContent\">");
      out.print( docContentValue );
      out.write("</textarea>\r\n");
      out.write("\r\n");
      out.write("                    <input type=\"file\" accept=\".txt\" onchange=\"readFile(this,'docContent')\">\r\n");
      out.write("\r\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-primary\">Ký tài liệu</button>\r\n");
      out.write("                </form>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"result-box\">\r\n");
      out.write("                    <strong>Chữ Ký Đã Sinh:</strong>\r\n");
      out.write("                    ");
 if(signR != null) { 
      out.write("\r\n");
      out.write("                        <div class=\"key-row\"><span class=\"key-label\">r:</span> <span class=\"key-value\">");
      out.print( signR );
      out.write("</span></div>\r\n");
      out.write("                        <div class=\"key-row\"><span class=\"key-label\">s:</span> <span class=\"key-value\">");
      out.print( signS );
      out.write("</span></div>\r\n");
      out.write("                    ");
 } else { 
      out.write("\r\n");
      out.write("                        <div class=\"placeholder\">Chưa có chữ ký.</div>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- BƯỚC 3 -->\r\n");
      out.write("        <div class=\"card\">\r\n");
      out.write("            <div class=\"card-header\">BƯỚC 3: XÁC MINH</div>\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("                <form action=\"process\" method=\"post\">\r\n");
      out.write("                    <input type=\"hidden\" name=\"action\" value=\"verify\">\r\n");
      out.write("\r\n");
      out.write("                    <label>Chữ ký (r,s)</label>\r\n");
      out.write("                    <textarea name=\"sigVerifyR\" id=\"sigVerify\">");

                        if(request.getAttribute("verify_sig_input") != null) out.print(request.getAttribute("verify_sig_input"));
                        else if(signR != null) out.print(signR + "," + signS);
                    
      out.write("</textarea>\r\n");
      out.write("\r\n");
      out.write("                    <input type=\"file\" accept=\".txt\" onchange=\"readFile(this,'sigVerify')\">\r\n");
      out.write("\r\n");
      out.write("                    <label>Văn bản gốc</label>\r\n");
      out.write("                    <textarea name=\"docVerify\" id=\"docVerify\">");

                        if(request.getAttribute("verify_doc_input") != null) out.print(request.getAttribute("verify_doc_input"));
                        else if(lastSignedDoc != null) out.print(lastSignedDoc);
                    
      out.write("</textarea>\r\n");
      out.write("\r\n");
      out.write("                    <input type=\"file\" accept=\".txt\" onchange=\"readFile(this,'docVerify')\">\r\n");
      out.write("\r\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-primary\">Xác minh</button>\r\n");
      out.write("                </form>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"verify-result-section\">\r\n");
      out.write("                    ");
 if(request.getAttribute("verify_checked") != null) {
                        boolean ok = (Boolean) request.getAttribute("verify_result");
                    
      out.write("\r\n");
      out.write("                        <div class=\"alert ");
      out.print( ok ? "alert-success" : "alert-danger" );
      out.write("\">\r\n");
      out.write("                            ");
      out.print( ok ? "CHỮ KÝ HỢP LỆ" : "CHỮ KÝ KHÔNG HỢP LỆ" );
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    ");
 } else { 
      out.write("\r\n");
      out.write("                        <div class=\"placeholder\">Chưa kiểm tra.</div>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"reset-card\">\r\n");
      out.write("        <form action=\"process\" method=\"post\">\r\n");
      out.write("            <input type=\"hidden\" name=\"action\" value=\"reset\">\r\n");
      out.write("            <button class=\"btn btn-danger reset-small\">Xóa toàn bộ dữ liệu</button>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
